import type { Metadata } from "next";
import "./globals.css"
import "./cover.module.css"
import "./footer.module.css"
import "./scenario.module.css"
import "./StatusStats.module.css"
import "./tamaguchi.module.css"
import "./title.module.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
